### ISSUE TITLE
Scarabs (id 1027): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#14]
**Scarabs of 2021-01-29**: fifth update since ac19 

previous reports: https://github.com/CatalogueOfLife/data/issues/154

- [x] Version in Metadata stated as Version 2020-10-06 Received by COL: 2020-10-06. Previous one. It means, version does not updated automatically via import.

**Comment by yroskov** [comment]
**TASKS** 2021-02-01
![image](https://user-images.githubusercontent.com/28574252/106479846-634c6d80-6470-11eb-991b-7dfd2647fc46.png)

- [x] Broken decisions: 84. Deleted all in 1027.  

Fixed:
![image](https://user-images.githubusercontent.com/28574252/106481268-e02c1700-6471-11eb-91a9-d9de4591b241.png)

**Comment by yroskov** [comment]
**ISSUES**

- [x] Multi Word Epithet (2) & Unusual Name Characters (2): two names blocked
synonym Eupotosia affinis tyrrenica fannyae Fiévet, 1995
synonym | Pinotus ascanius piceus rotundiceps Luederwaldt, 1930

**Comment by yroskov** [comment]
**Synced on 2021-02-01**

**Comment by yroskov** [comment]
**Scarabs of 2021-03-01: sixth update since ac19**

Imported on 2021-03-01.

**Comment by yroskov** [comment]
ISSUES 2021-03-01

- [ ] **Partially Parsable Name** (3): 0 at the end of second epithet (reported to Paul)
https://data.catalogueoflife.org/catalogue/3/dataset/1027/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=partially%20parsable%20name&limit=100&offset=0
Onthophagus (Onthophagus) polyphemi polyphemi0 Hubbard, 1894
Pygopleurus psilotrichius psilotrichius0 (Faldermann, 1835)
Silphotrupes escorialensis escorialensis0 (Jekel, 1865) |

**Comment by yroskov** [comment]
**Scarabs of 2021-03-01 synced on 2021-03-02.**

**Comment by yroskov** [comment]
**Scarabs of 2021-03-29: eigth update since ac19**

Imported & re-imported after fixes on 2021-03-29 as id1027.

>>Dear Paul,
Thanks for the update--it's imported. It looks like there's a few invalid parent IDs which resulted in some taxa being excluded from the superfamily:
https://data.catalogueoflife.org/dataset/1027/issues
https://data.catalogueoflife.org/dataset/1027/classification
Beyond those issues, there was one invalid GSDNameStatus='FUJ-016' record in the Synonyms table that caused the converter to crash in this record:
CODE    Genus
"00-.04-.18-.00-.020-.000-.000-.-"    "Homoderinus"
Best regards,
Geoff

**Comment by yroskov** [comment]
**TASKS** 2021-03-29

![image](https://user-images.githubusercontent.com/28574252/112895546-e53cc980-90a2-11eb-9180-c906deae363c.png)

- [x] **Broken decisions**, 187. Rematch all = remains 17. Deleted all broken.

Resolved:

![image](https://user-images.githubusercontent.com/28574252/112896239-c559d580-90a3-11eb-80ea-61192e65c28e.png)

**Comment by yroskov** [comment]
**Scarabs of 2021-03-29 synced on 2021-03-29.**

**Comment by yroskov** [comment]
**Scarabs of 2021-04-27: 9th update since ac19**

![image](https://user-images.githubusercontent.com/28574252/116441285-efbfbf80-a816-11eb-9ed2-8067291beaef.png)

**Comment by yroskov** [comment]
**Scarabs of 2021-06-01: 10th update since ac19**

- [ ] Metadata: problem with a patch (version & dates was not correctly updated) - https://github.com/CatalogueOfLife/backend/issues/1017

- [x] Sector: OK

- [x] ISSUES: assessed; no changes

- [x] TASKS

![image](https://user-images.githubusercontent.com/28574252/121062256-7a86c900-c78a-11eb-98f1-6d4568abc5ee.png)

- [x] Broken decisions, 11. Rematched one-by-one: 10 remain broken. Deleted.

Resolved:
![image](https://user-images.githubusercontent.com/28574252/121062646-f719a780-c78a-11eb-91aa-5737131307c5.png)

**Comment by yroskov** [comment]
**Scarabs of 2021-06-30**: 11th update since ac19 

TASKS

![image](https://user-images.githubusercontent.com/28574252/124036944-64a0a880-d9c4-11eb-97e1-f30e5028e6b1.png)

**Scarabs of 2021-06-30 synced 2021-06-30**

**Comment by yroskov** [comment]
**Scarabs of 2021-08-04**, first update after ac21.

ISSUES:
![image](https://user-images.githubusercontent.com/28574252/130116664-8154736e-659b-4e12-b281-159490050bf0.png)

TASKS:
![image](https://user-images.githubusercontent.com/28574252/130116599-c72cba93-c86a-42f4-8d2f-f2ddbfc89ded.png)

Synced 2021-08-19.

**Comment by yroskov** [comment]
Scarabs of 2021-09-01. No issues.
Synced 2021-09-03.

**Comment by yroskov** [comment]
Paul, 2021-11-02:
>I checked COL version 10-18 and quite a lot is missing, can not find the reason
Examples:
**Trox cadaverinus** missing
**Trox sonorae** missing
**Trox sabulosus** Linneaus 1758 missing
These are some of the issues in “accepted name missing, accepted id invalid”
For my update of November, I think it is better to send a database with only the fields used by Col, to avoid any disturbance.
I shall send an update in following days

YR checked these names in the checklistbank: they marked there as "bare names". 
Example for _Trox cadaverinus_:
https://data.catalogueoflife.org/dataset/1027/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Trox%20cadaverinus&sortBy=taxonomic

![image](https://user-images.githubusercontent.com/28574252/139940664-1107d757-7d35-4d31-9850-1b997854313a.png)

**Comment by yroskov** [comment]
**Scarabs of 2021-11-03** (new version after crawler fix) imported. 

- [x] Imported: 40729 spp
- [x] Sector: OK 
- [x] ISSUES assessed
![image](https://user-images.githubusercontent.com/28574252/140182987-a9982e9b-d759-4864-bab2-285cd1ce3995.png)

Import timeline:
![image](https://user-images.githubusercontent.com/28574252/140184540-244565c5-7cfa-4341-8712-de3e7aad8821.png)

TASKS
![image](https://user-images.githubusercontent.com/28574252/140184813-708a5221-87f9-47de-804d-8ffe99555f32.png)

- [x] Broken decisions, 3. Rematch failed. All deleted.

**Comment by yroskov** [comment]
**Scarabs of 2021-12-06** imported. 

- [x] Imported: 40776 spp
- [ ] Sector:  
- [ ] ISSUES 
![image](https://user-images.githubusercontent.com/28574252/145881739-5b884129-efc0-4d33-8c14-a60f00588a13.png)

TASKS

**Comment by yroskov** [comment]
**New version 2021-12-13**

**Comment by yroskov** [comment]
**Scarabs of 2021-12-13** imported 2021-12-14 
 
- [x] Imported: 40773 spp
- [x] Metadata: date OK
- [x] Sector:  ok
- [ ] Classification: 2 genera with 7 species are in the tree root, i.e. outside superfamily Scarabaeoidea (much less than in previous version = improvement)
![image](https://user-images.githubusercontent.com/28574252/146084197-c961d11c-f465-4a8d-b92a-ddeed62c1b5c.png)

ISSUES
![image](https://user-images.githubusercontent.com/28574252/146084486-31b50edf-ee0c-4bf5-9616-21301b287395.png)

TASKS
![image](https://user-images.githubusercontent.com/28574252/146086666-b7bd3587-1327-4b1c-97ca-c9a9f12e8d87.png)

- [x] Broken decision, 1. Rematched successfully.

**Comment by yroskov** [comment]
Scarabs of 2022-01-10 imported 2022-01-10

- [x] Imported: 40866 spp
![image](https://user-images.githubusercontent.com/28574252/149197996-7a3d68bc-feb2-425e-9664-b2f4fcbf2b36.png)
- [x] Metadata: date OK
- [x] Sector: ok
- [x] Classification: ok

ISSUES
![image](https://user-images.githubusercontent.com/28574252/149198467-ea7cee5e-57e6-4d38-ac64-47ad94fdef5b.png)

TASKS = all are OK
![image](https://user-images.githubusercontent.com/28574252/149198253-bf90e867-06f3-43ba-a5ac-6714e0ccaacf.png)

- [x] Broken decisions, 9. Rematch all = 2 broken left. All deleted.

**Synced 2022-01-12**

**Comment by yroskov** [comment]
**Scarabs of 2022-02-17** imported 2022-02-17 (the 2nd version after fixes in version received on 2022-02-02) 
 
- [x] Imported: 40896 spp
- [x] Metadata: date OK, 2022-02-17 / 2022-02-17
- [x] Sector:  ok
- [x] Classification: OK. Only one species Tonkinella graminea is in the root
![image](https://user-images.githubusercontent.com/28574252/154566124-b5fe694d-d915-4fa4-9e34-02692645df97.png)

ISSUES assessed
![image](https://user-images.githubusercontent.com/28574252/154566504-7b9a3953-24dc-4892-b9c0-411992732609.png)

TASKS
![image](https://user-images.githubusercontent.com/28574252/154566674-b2347dc9-5059-4f02-a5d9-25c5cd1fa978.png)

- [x] Broken decision, 214. Rematched; 4 remain broken = deleted.

Resolved:
![image](https://user-images.githubusercontent.com/28574252/154569601-36dce5af-bdc9-4b17-9a6d-ad5e65ab3adb.png)

**Synced 2022-02-17**

**Comment by yroskov** [comment]
Revisiting "decisions" after fixes https://github.com/CatalogueOfLife/testing/issues/184#issuecomment-1055567444

TASKS 2022-03-04
![image](https://user-images.githubusercontent.com/28574252/156836667-c8c197c4-1208-4c90-a258-78abac1b258c.png)

Resolved 2022-03-04:
![image](https://user-images.githubusercontent.com/28574252/156837224-8c917d24-591b-4cda-8605-44bd3f9eb9e9.png)

Synced 2022-03-04

**Comment by yroskov** [comment]
- [ ] The name **Diplotaxis denticeps** Bates, 1887 is missing. Why? 

Paul, 2022-03-06: 
>Dear Geoff and Yuri,
Following problem mentioned by a user
[https://urldefense.com/v3/__https://data.catalogueoflife.org/dataset/1027/__;!!DZ3fjg!ty0XOcRyqUTed6zeXGZaJ6o2r25cn50-RouxV28Nnf6z3b_TE8Ek1Y119iT7mEBwJgI$](https://urldefense.com/v3/__https:/data.catalogueoflife.org/dataset/1027/__;!!DZ3fjg!ty0XOcRyqUTed6zeXGZaJ6o2r25cn50-RouxV28Nnf6z3b_TE8Ek1Y119iT7mEBwJgI$) 
Browse
**Diplotaxis denticeps** Bates, 1887
[https://urldefense.com/v3/__https://www.catalogueoflife.org/data/browse__;!!DZ3fjg!ty0XOcRyqUTed6zeXGZaJ6o2r25cn50-RouxV28Nnf6z3b_TE8Ek1Y119iT7INHafnM$](https://urldefense.com/v3/__https:/www.catalogueoflife.org/data/browse__;!!DZ3fjg!ty0XOcRyqUTed6zeXGZaJ6o2r25cn50-RouxV28Nnf6z3b_TE8Ek1Y119iT7INHafnM$) 
**this record not present**
Via search also not found
Reason ??
Kind regards

My search result in CLB Workbench **inside the project** 2022-03-07:
>Request failed with status code 404
EditorialDecision 3:17034 does not exist
HTTP method: GET
https://api.checklistbank.org/dataset/3/decision/17034

![image](https://user-images.githubusercontent.com/28574252/157060548-58a3954b-c8c3-4701-832e-c5d86ff684e3.png)

Search result in CLB **Search outside the project** 2022-03-07:
_Name is present, no any decisions displayed_
![image](https://user-images.githubusercontent.com/28574252/157061063-2601ccef-4548-421b-a7b4-e41d84b3376d.png)

@mdoering, would it be related to this fixes: https://github.com/CatalogueOfLife/data/issues/397 ?

**Comment by mdoering** [comment]
It is clearly present in the current working draft: https://www.checklistbank.org/catalogue/3/taxon/e33be22e-16a4-4421-869d-608bf49f39a4

But it is not in the latest release nor in any release from CLB. Odd. 
They are based on the same import attempt, so both versions should be identical!

**Comment by mdoering** [comment]
Counting the number of name usages in the current draft and the latest release that come from the 588 sector of scarabs this yields 78947 and 78939 respectively, a difference of 8! Comparing other sectors all yield the exact same count. Still looking...

**Comment by mdoering** [comment]
These are Scarabs names present in the draft, but not in the latest release. Why I still don't know:

```
col=> select u.id, n.rank, u.status, n.scientific_name, n.authorship from name_usage_3 u join name_3 n on n.id=u.name_id where u.sector_key=588 and not exists (select s.id from name_usage_9804 s join name_9804 sn on sn.id=s.name_id where sn.scientific_name=n.scientific_name and sn.authorship=n.authorship and sn.rank=n.rank);
                  id                  |        rank        |  status  |         scientific_name          |               authorship               
--------------------------------------+--------------------+----------+----------------------------------+----------------------------------------
 de68e545-e78f-4b06-a64c-54be0d0f1b8b | GENUS              | SYNONYM  | Maneschetocia                    | 
 e33be22e-16a4-4421-869d-608bf49f39a4 | SPECIES            | ACCEPTED | Diplotaxis denticeps             | Bates, 1887
 9054418e-0560-47fb-bd2d-98d45bb41caa | SPECIES            | ACCEPTED | Anomala matsumurai               | Sawada, 1950
 1649994e-af9e-44cd-8e56-8bcf6791fe0e | INFRASPECIFIC_NAME | SYNONYM  | Diplotaxis trapezifera denticeps | Bates, 1887
 ba81d6b8-6597-4d07-879a-3afb8fd788e1 | SUPERFAMILY        | ACCEPTED | Scarabaeoidea                    | 
 0cdf5907-e520-42a2-9139-45f31cb77cb2 | GENUS              | SYNONYM  | Pseuduroxys                      | 
 14c68132-5df7-49ca-bd1d-dc06346ec846 | SPECIES            | ACCEPTED | Trizogeniates curvatus           | Ferreira, Bravo, Grossi & Seidel, 2019
 f79e4f29-3ab3-42f4-b1b9-a66438c47948 | SUBSPECIES         | ACCEPTED | Xenopelidnota anomala porioni    | Chalumeau, 1985
 bfcbb4c4-a5da-4fda-9a00-8da92c63d583 | INFRASPECIFIC_NAME | SYNONYM  | Anomala matsumurai tokarana      | Nomura, 1961
 fd2ed6b2-3509-43a6-bd6b-9b08e0b5bfb3 | SPECIES            | SYNONYM  | Anomala cpustulata               | Matsumura, 1940
 7838a02a-9f25-4a39-a2fd-e2d0262e65f2 | INFRASPECIFIC_NAME | SYNONYM  | Anomala aenea bicolor            | Schilsky, 1888
(11 rows)
```

**Comment by yroskov** [comment]
Update for "**The name Diplotaxis denticeps Bates, 1887 is missing**" 2022-03-08:

Search for _Diplotaxis denticeps_ works now (at least, for me) on **prod** INSIDE the project and in Assembly:
https://www.checklistbank.org/catalogue/3/dataset/1027/classification?taxonKey=18-.08-.01-.00-.001-.000-.219-.-
https://www.checklistbank.org/catalogue/3/assembly?assemblyTaxonKey=e33be22e-16a4-4421-869d-608bf49f39a4

![image](https://user-images.githubusercontent.com/28574252/157275882-8a25f852-89d3-4362-9270-91d265ed1a99.png)
![image](https://user-images.githubusercontent.com/28574252/157275618-17b0a666-3fd5-4732-86dd-68fa9155ad8b.png)

However, search for _Diplotaxis denticeps_ does not work on **dev** in Assembly (after sync):
https://www.dev.checklistbank.org/catalogue/3/assembly?datasetKey=1027
![image](https://user-images.githubusercontent.com/28574252/157276703-7b40c8f0-a0f2-441d-a115-797b61f0ad01.png)

But, search for _Diplotaxis denticeps_ works INSIDE the project.

**Comment by yroskov** [comment]
**Scarabs of 2022-03-14** imported 2022-03-14 

- [x] Imported: 40916 spp
- [x] Metadata: date OK, 2022-03-14 
- [x] Sector: ok
- [x] Classification: OK. (no species in the root)

ISSUES assessed 2022-03-17

TASKS, no issues 2022-03-17
Github: Something went really wrong, and we can't process that file
- [x] Broken decisions: 5; rematchAll = 5; deletedAll

**Synced 2022-03-17**

**Comment by yroskov** [comment]
**Scarabs of 2022-04-11** imported 2022-04-11

- [x] Imported: 40943 spp
- [x] Metadata: date OK, 2022-04-11
- [x] Sector: ok
- [x] Classification: OK. (no species in the root)

TASKS 
![image](https://user-images.githubusercontent.com/28574252/163881701-407fac8a-6883-4563-9310-9dd65f3a349f.png)

Resolved 2022-04-18
![image](https://user-images.githubusercontent.com/28574252/163882373-a2231341-456f-4690-9b76-84f0766f1686.png)

**Synced 2022-04-18**

**Comment by yroskov** [comment]
**Scarabs of 2022-05-02** imported 2022-05-04

- [x] Imported: 40948 spp
- [x] Metadata: date OK, 2022-05-02
- [x] Sector: ok
- [x] Classification: OK

TASKS 
![image](https://user-images.githubusercontent.com/28574252/166955430-ee69e413-c031-450f-b5ac-6e0c75cda82f.png)

Resolved (deleted broken decisions)
![image](https://user-images.githubusercontent.com/28574252/166955790-b2207afd-dafe-4a22-9623-4b9f3cc87fcf.png)

**Comment by yroskov** [comment]
**Scarabs of 2022-07-06** imported 2022-07-06

- [x] Imported: 40987 spp
- [x] Metadata: ok
- [x] Sector: ok

**Comment by yroskov** [comment]
**Scarabs of 2022-08-03** imported 2022-08-03

- [x] Imported: 41105 spp
- [x] Metadata: ok
- [x] Sector: ok

TASKS 
![image](https://user-images.githubusercontent.com/28574252/182633299-30850697-4eb8-4f56-bdc7-dd25853e6e1c.png)

Resolved 2022-08-03:
![image](https://user-images.githubusercontent.com/28574252/182634903-29083199-eea1-4bea-90e9-65abbcb96b2e.png)

**Synced 2022-08-03**

**Comment by yroskov** [comment]
**Scarabs of 2022-09-06** imported 2022-09-06

- [x] Imported: 41120 spp
- [x] Metadata: ok
- [x] Sector: ok

TASKS 
![image](https://user-images.githubusercontent.com/28574252/191107914-b5522cd3-1a32-49c4-b188-337219d8af8f.png)

**Synced 2022-09-19**

**Comment by mdoering** [comment]
Checking the issues page there are several published before genus cases: https://www.checklistbank.org/dataset/1027/verbatim?issue=published%20before%20genus

The publishedInYear is wrongly populated with the original names publication. Its supposed to be the publication of the exact combination, not the "basionym". If unknown keep it blank

**Comment by yroskov** [comment]
**Scarabs of 2022-10-05**; imported 2022-10-05

- [x] Imported: 41197 spp
- [x] Metadata: ok
- [x] Classification: ok 
- [x] Sector: ok

TASKS 
![image](https://user-images.githubusercontent.com/28574252/194898744-24da7b05-ff21-4840-8e32-52dd69522952.png)

- Broken decisions, 1: deleted

Resolved 2022-10-10
![image](https://user-images.githubusercontent.com/28574252/194908786-50f551be-96b6-4200-bfa6-74217b4e77b7.png)

**Synced 2022-10-10**

**Comment by yroskov** [comment]
**Scarabs of 2022-11-08**; imported 2022-11-09

- [x] Imported: 41212 spp (va 41197)
- [x] Metadata: ok
- [ ] Classification: one species Melanopopillia (Stagonopertha) carinicollis (Ohaus, 1905) is the root (out of families)
- [x] Sector: ok

TASKS

**Comment by yroskov** [comment]
**Scarabs of 2022-12-01**; imported 2022-12-01

- [x] Imported: 41232 spp (vs 41212 spp)
- [x] Metadata: ok
- [x] Classification: ok
- [x] Sector: ok

ISSUES

![image](https://user-images.githubusercontent.com/28574252/205368714-5a36d383-aad6-4790-9f79-88f9c6738dcc.png)

TASKS

![image](https://user-images.githubusercontent.com/28574252/205368801-e7cf0b4b-da96-472b-8873-cc9d66c89012.png)

- Broken decisions, 31: deleted

Resolved 2022-12-02:

![image](https://user-images.githubusercontent.com/28574252/205369577-69bfa718-0859-4e7e-b3c7-2aadebbb20ce.png)

**Synced 2022-12-02**

**Comment by yroskov** [comment]
**Scarabs of 2023-01-03**; imported 2023-01-03

- [x] Imported:  41245 spp (vs 41232 spp)
- [x] Metadata: ok
- [x] Classification: ok
- [x] Sector: ok

![image](https://user-images.githubusercontent.com/28574252/210415388-3cd9acce-4102-4e7b-8a7b-21d8448742f6.png)

![image](https://user-images.githubusercontent.com/28574252/210415622-0a99e18d-511c-437f-a556-02ad4bc1345c.png)

ISSUES
![image](https://user-images.githubusercontent.com/28574252/210415861-ef86d935-6278-4ad9-bd1a-e14cc8fe35db.png)

TASKS
![image](https://user-images.githubusercontent.com/28574252/210416105-f821d29a-615e-4ae4-a7ce-d50eff618132.png)

- Broken decisions, 8: deleted all

**Comment by yroskov** [comment]
**Scarabs of 2023-02-06**; imported 2023-02-0

- [ ] Imported:   spp (vs 41245 spp)
- [ ] Metadata: 
- [ ] Classification: 
- [ ] Sector:

**Comment by yroskov** [comment]
**Scarabs of 2023-03-06**; imported 2023-03-06

- [x] Imported:  41312 spp (vs 41251 spp)
- [x] Metadata: OK
- [x] Classification: OK 
- [x] Sector: OK

TASKS

![image](https://user-images.githubusercontent.com/28574252/223217067-9bbaaf03-de27-44f4-a36f-7adc0e32029f.png)

- Broken decisions, 3: 2 rematched, 1 deleted

**Synced 2023-03-06**

**Comment by yroskov** [comment]
**Scarabs of 2023-04-04**; imported 2023-04-06

- [x] Imported:  41339 spp (vs 41312 spp)
- [x] Metadata: OK
- [x] Classification: OK 
- [x] Sector: OK

![image](https://user-images.githubusercontent.com/28574252/230621972-954fafee-9198-4e1f-a133-47f23ef35f21.png)

TASKS

![image](https://user-images.githubusercontent.com/28574252/230657345-c5e493bf-f1b9-4c5d-b97e-0f4dbb98345c.png)

- Broken decisions, 132

Resolved 2023-04-07:

![image](https://user-images.githubusercontent.com/28574252/230661768-1282f6c1-eeda-4385-8934-f59280d07185.png)

**Synced 2023-04-07**

**Comment by yroskov** [comment]
**Scarabs of 2023-05-09**; imported 2023-05-09

- [x] Imported:  41370 spp (vs 41339 spp)
- [x] Metadata: OK
- [x] Classification: OK 
- [x] Sector: OK

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e63ca1a7-98dd-4925-a0f2-86ff42da123a)

ISSUES 

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/090df502-f8da-4f6a-abe7-9becba888ad2)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/383cf673-19ee-47be-9092-5cb6fffee4ee)

- Broken decisions, 61: deleted all

Resolved 2023-05-09:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/40ae6eb1-d2b0-435a-80c2-8d5092b65dc3)

**Synced 2023-05-09**

**Comment by yroskov** [comment]
**Scarabs of 2023-08-01**; imported 2023-08-07

- [x] Imported: 41386 spp (vs 41393 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3de03411-63ca-4628-be15-12c7a75149ed)

ISSUES assessed 2023-08-07

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/52790bc4-ca7a-43b0-b28a-81f83404288d)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/49671992-ca75-4cee-82af-9b6beab3cc11)

Where is a report on broken decisions?

**Comment by yroskov** [comment]
**Scarabs of 2023-11-06**; imported 2023-11-06

- [x] Imported: 41483 spp (vs 41398 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c01c2ce9-4e08-413d-9adf-14e95d8c32bd)

ISSUES assessed 2023-11-07

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/6420e0c9-482a-4d53-9adc-0b1550a833ec)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c34b5156-b918-4f35-994f-b93ae3c1ae45)

- Broken decisions, 7: deleted

Resolved 2023-11-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/4e46ed9e-e223-41fe-b425-160fb82807c1)

**Synced 2023-11-07**

**Comment by yroskov** [comment]
**Scarabs of 2024-01-08**; imported 2024-01-08

- [x] Imported: 41535 spp (vs 41514 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/45e6db29-31b4-47d7-ad61-78310619fce4)

TASKS 

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f1de0ab6-6877-472a-bdc6-97924754e69e)

- Broken decisions, 5: deleted
- Outdated decisions, 7: deleted

**Synced 2024-01-16**

**Comment by yroskov** [comment]
**Scarabs of 2024-02-05**; imported 2024-02-05

- [x] Imported: 41555 spp (vs 41535 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/cf645604-266c-4d06-95e5-f79b5e42fe26)

TASKS = no issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1fed5440-babc-481a-a487-9cafa1043c6f)

**Synced 2024-02-05**

**Comment by yroskov** [comment]
**Scarabs of 2024-03-05**; imported 2024-03-05

- [x] Imported: 41627 spp (vs 41555 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

METRICS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/49d50044-1dc3-49a5-8475-74f3e660f5d8)

ISSUES assessed 2024-03-05

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/fea6a5dc-3848-40f1-90f9-67c53bba90f1)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/ee22d3b0-f9ba-44c9-8910-5b6c51a76761)

- Broken decisions, 4 = deleted

**Comment by yroskov** [comment]
**Scarabs of 2024-04-01**; imported 2024-04-01

- [x] Imported: 41657 spp (vs 41627 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8c02340d-ff1d-4c69-86b9-a6ed67412bac)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/0d3c7648-284c-4328-9a87-85cd5fcbfa81)

- Broken decisions, 14 = deleted

Resolved 2024-04-01:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/96a0f8da-ae01-4615-bc48-24688401d071)

**Synced 2024-04-01**

**Comment by yroskov** [comment]
**Scarabs of 2024-05-06**; imported 2024-05-06;

- [x] Imported: 41667 spp (vs 41657 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/fb186dc9-e66b-4d5c-8d3e-7be4bb706764)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bc162ac0-a727-4c47-b60e-1c3593a8d489)

- Broken decisions, 13 = deleted

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/ff4f9f61-c1be-4c74-a357-f28f5316f715)

**Synced 2024-05-07**

**Comment by yroskov** [comment]
**Scarabs of 2024-06-03**; imported 2024-06-03

- [x] Imported: 41675 spp (vs 41667 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/364d47d9-f9e2-4e73-8383-2c5689ae4fc6)

ISSUES assessed 2024-06-03

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7d4b6dcf-5e48-4747-86b0-f18abd54b1d5)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/661745d6-01ce-4e22-b7c7-387a83a4834c)

- Broken decisions, 58 = deleted all

Resolved 2024-06-03:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/73c750f8-2e13-4889-83a3-9d3f6c8249b1)

**Synced 2024-06-03**

**Comment by yroskov** [comment]
**Scarabs of 2024-07-08**; imported 2024-07-08

- [x] Imported: 41684 spp (vs 41675 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/ae4919ec-947f-446b-8d41-ed666782fe59)

TASKS no new issues

**Synced 2024-07-08**

**Comment by yroskov** [comment]
**Scarabs of 2024-08-05**; imported 2024-08-05

- [x] Imported: 41735 spp (vs 41684 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/user-attachments/assets/f766c4d0-79de-4a02-af7f-bc1be4f83bb7)

ISSUES assessed 2024-08-06

![image](https://github.com/user-attachments/assets/0fdcdc62-3aab-4c27-9077-a442715e04d5)

TASKS

![image](https://github.com/user-attachments/assets/b0d8f189-7415-427b-92a6-220b60aa0b80)

Resolved 2024-08-06:

![image](https://github.com/user-attachments/assets/86ddc321-daa6-4662-b50c-f39872a9ff75)

**Synced 2024-08-06**

**Comment by yroskov** [comment]
**Scarabs of 2024-09-03**; imported 2024-09-03

- [x] Imported: 41745 spp (vs 41735 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/user-attachments/assets/56bc2a10-208f-4d81-bfc9-267dfae075a9)

TASKS = no new issues

![image](https://github.com/user-attachments/assets/a14687b1-429f-42fb-9ace-34274ad8944f)

**Synced 2024-09-11**

**Comment by yroskov** [comment]
**Scarabs of 2024-10-09**; imported 2024-10-09

- [x] Imported:  41775 spp (vs 41745 spp)
- [x] Metadata: OK
- [x] Classification: OK (there are changes in the generic list - new subgenera added; some former genera degraded to subgenera https://www.checklistbank.org/dataset/1027/diff?attempts=132..135)
- [x] Sector: OK

Metrics

![image](https://github.com/user-attachments/assets/d8b60f56-227a-4ed6-9d2e-64992f805be7)

ISSUES assessed 2024-10-09

![image](https://github.com/user-attachments/assets/cd4eaec6-0fce-4763-afcc-868e6c3869d4)

TASKS

![image](https://github.com/user-attachments/assets/24622a9f-1600-4012-9d37-61c78593cacf)

- Broken decisions, 23 = deleted
- Outdated decisions, 2 = no action

Resolved 2024-10-09:

![image](https://github.com/user-attachments/assets/96c27fe0-8c71-4652-8c18-7d0e449cbdd2)

**Synced 2024-10-09**

**Comment by yroskov** [comment]
**Scarabs of  2024-11-04**; imported  2024-11-04

- [x] Imported:  41797 spp (vs 41775 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/user-attachments/assets/d653be2c-d6e9-489d-8501-ddcd8977e6da)

TASKS

![image](https://github.com/user-attachments/assets/f276168e-2a24-48b7-99f1-2557c6d5274f)

Resolved 2024-11-06:

![image](https://github.com/user-attachments/assets/90d3f247-2f56-4e64-a0bc-02f1b2b94e9c)

**Synced 2024-11-06**

**Comment by gdower** [comment]
**Scarabs of  2024-12-04**; imported  2024-12-04

- [x] Imported: 41818 spp (vs 41797 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/user-attachments/assets/1acd87e1-d850-44ed-aa11-33d736f9438d)

TASKS

![image](https://github.com/user-attachments/assets/6fa5e9ff-1d8c-4d9c-a037-8d62e5021b55)

**Synced 2024-12-04**

**Comment by yroskov** [comment]
**Scarabs of 2025-01-06 / 2025-01-06**; imported 2025-01-06

- [x] Imported: 41849 spp (vs 41818 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![image](https://github.com/user-attachments/assets/c1937ef5-bf85-42cf-b43b-04343396d515)

TASKS

![image](https://github.com/user-attachments/assets/0aefc813-52e6-4eb8-bb94-2326607ae40d)

- Broken decisions, 14 = deleted
- Outdated decisions, 1 = no action

Resolved 2025-01-08:

![image](https://github.com/user-attachments/assets/16247475-0d3d-497a-812f-1621cc4be9e2)

**Synced 2025-01-08**

**Comment by yroskov** [comment]
**Scarabs of 2025-02-05 / 2025-02-05**; imported 2025-02-06

- [x] Imported: 41861 spp (vs 41849 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![Image](https://github.com/user-attachments/assets/fb27a0e0-6794-4451-bc49-bdd36e1da72c)

TASKS

![Image](https://github.com/user-attachments/assets/5ab97c9b-249c-4ba2-9fcd-d37baf748e8c)

- Broken decisions, 1 = deleted

Resolved 2025-02-06:

![Image](https://github.com/user-attachments/assets/e21ef663-e286-4137-ba7e-8bb2717b9b7a)

**Synced 2025-02-06**

**Comment by yroskov** [comment]
**Scarabs of 2025-03-04 / 2025-03-04**; imported 2025-03-04

- [x] Imported: 41902 spp (vs 41861 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK

Metrics

![Image](https://github.com/user-attachments/assets/9809dc6d-147a-4b82-a031-36b449cae8a4)

TASKS

![Image](https://github.com/user-attachments/assets/a850d127-32c9-46bb-b1d1-c14fc7255ee7)

Resolved 2025-03-04:

![Image](https://github.com/user-attachments/assets/33e5d14c-9f20-4c2b-b853-0d30e37c2a42)

**Synced 2025-03-04**

**Comment by yroskov** [comment]
**Scarabs of 2025-04-02 / 2025-04-02**; imported 2025-04-02

- [x] Imported: 41926 spp (vs 41902 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK

Metrics

![Image](https://github.com/user-attachments/assets/1f772556-7b37-4d59-8105-8ae86fd1e00a)

TASKS

![Image](https://github.com/user-attachments/assets/20bb24bc-6129-4f3c-87c5-302d190be9c6)

- Broken decisions, 38 = deleted
- Outdated decisions, 1 = no action

Resolved 2025-04-02:

![Image](https://github.com/user-attachments/assets/f897a447-5c09-4d9c-9bf8-7e3dd4ee897d)

- [x] There are two entries for accepted genus **Phanaeus MacLeay, 1819** (with 0 species) and **Phanaeus Edmonds, 1994** (with 83 spp).  Both are in subtribe Phanaeina (superfamily: Scarabaeoidea > family: Scarabaeidae > subfamily: Scarabaeinae > tribe: Phanaeini > subtribe: Phanaeina).
Paul, 2025-04-02: _The Edmonds record (new synonym) is the subgenus Notiophanaeus, the  83 spp belong to Phanaeus (s.str.) of MacLeay_ = need to be fixed in master database (I temporarily fixed via complex & block decisions; all children species are in correct genus, few generic synonyms lost = re-synced 2025-04-02). = FIXED in the master 2025-04-03

**Synced 2025-04-02**

========================

**Scarabs of 2025-04-03 / 2025-04-03**; imported 2025-04-03 = SECOND ITERATION with fixes made in the master database

- [x] Imported: 41930 spp (vs 41926 spp)

TASKS

![Image](https://github.com/user-attachments/assets/0e74aebb-3e5a-4ca8-b562-feb0c0218b5a)

Resolved 2025-04-03:

![Image](https://github.com/user-attachments/assets/1fd5e874-4df4-4b91-a356-ead651e48091)

**Re-synced 2025-04-03**

**Comment by yroskov** [comment]
**Scarabs of 2025-05-05 / 2025-05-05**; imported 2025-05-05

- [x] Imported: 41948 spp (vs 41926 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK

Metrics

![Image](https://github.com/user-attachments/assets/a8bbe4b6-18c0-4929-826b-5fff8ccf754f)

TASKS

![Image](https://github.com/user-attachments/assets/bf29414d-2a5b-4174-bc67-dcd56c36b09b)

Resolved 2025-05-05:

![Image](https://github.com/user-attachments/assets/4aa49420-9289-4145-b076-488962650c26)

**Synced 2025-05-05**

**Comment by yroskov** [comment]
**Scarabs of 2025-06-02 / 2025-06-02**; imported 2025-06-02

- [x] Imported: 41957 spp (vs 41948 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK (354 spp, 115 gen, 6 tribes, 14 subfam, 3 fam)

Metrics

![Image](https://github.com/user-attachments/assets/f961c766-111d-4c9f-86bb-f79e137f09e8)

ISSUES assessed 2025-06-02

![Image](https://github.com/user-attachments/assets/c366abae-2da8-4ad0-b76d-e10281a42427)

TASKS = no new issues

![Image](https://github.com/user-attachments/assets/13d20cc0-955c-4cc3-9302-cdbc22b01fda)

**Synced 2025-06-02**

**Comment by yroskov** [comment]
**Scarabs of 2025-06-24**; imported 2025-06-24
(_after media inclusion in CoLDP_) 

- [x] Imported: 41966 spp (vs 41957 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK (354 spp, 115 gen, 6 tribes, 14 subfam, 3 fam)

Metrics

![Image](https://github.com/user-attachments/assets/846ae573-9335-4f1f-8524-3ea494af5545)

ISSUES assessed 2025-06-30

![Image](https://github.com/user-attachments/assets/44b9a8a0-e938-49c1-9284-b3df741686e8)

TASKS

![Image](https://github.com/user-attachments/assets/fa82f833-900f-4c05-b19b-b3e45b129fd7)

- Broken decisions, 3 = deleted
- Outdated decisions, 1 = deleted

Resolved 2025-06-30:

![Image](https://github.com/user-attachments/assets/0fe1ff1d-06c1-4ffc-adf8-a5924e00090d)

**Synced 2025-06-30**

**Comment by yroskov** [comment]
**Scarabs of 2025-07-31**; imported 2025-08-01

- [x] Imported: 41980 spp (vs 41966 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK (354 spp, 115 gen, 6 tribes, 14 subfam, 3 fam)

Metrics

<img width="1444" height="4779" alt="Image" src="https://github.com/user-attachments/assets/117cc24b-f77e-45cd-8669-3da923e094bb" />

TASKS = no new issues

**Synced 2025-08-01**

**Comment by yroskov** [comment]
**Scarabs of 2025-09-08**; imported 2025-09-08

- [x] Imported: 41996 spp (vs 41980 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK (354 spp, 115 gen, 6 tribes, 14 subfam, 3 fam)

Metrics

<img width="1466" height="4899" alt="Image" src="https://github.com/user-attachments/assets/6cb2ae9f-ae5c-4bc3-a122-2ba5bbbe6bdf" />

TASKS = no new issues

**Synced 2025-09-08**

**Comment by yroskov** [comment]
**Scarabs of 2025-10-07**; imported 2025-10-07

- [x] Imported: 42048 spp (vs 41996 spp)

TASKS

<img width="1591" height="1063" alt="Image" src="https://github.com/user-attachments/assets/bf729f1e-459e-42d8-8604-3749228e9721" />

- Broken decisions, 1 = deleted

Resolved 2025-10-08:

<img width="1591" height="1047" alt="Image" src="https://github.com/user-attachments/assets/5f65e106-5ee2-4a32-ba36-381aeac54729" />

**Synced 2025-10-08**

**Comment by yroskov** [comment]
**Scarabs of 2025-11-04**; imported 2025-11-04

- [x] Imported: 42074 spp (vs 41996 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK (356 spp, 116 gen, 6 tribes, 14 subfam, 3 fam)

Metrics

<img width="1945" height="6024" alt="Image" src="https://github.com/user-attachments/assets/bc3fd2ae-fe98-47d6-b93f-18fb08feeab1" />

TASKS

<img width="1637" height="1203" alt="Image" src="https://github.com/user-attachments/assets/0cf332c3-f3c2-483a-a555-031624e9ee68" />

- Broken decisions, 5 = deleted

Resolved 2025-11-07:

<img width="1652" height="1184" alt="Image" src="https://github.com/user-attachments/assets/9f77f1f8-a7d3-4e45-bd86-fccb6a5a03d5" />

**Synced 2025-11-07**

**Comment by yroskov** [comment]
**Scarabs of 2025-12-01**; imported 2025-12-01

- [x] Imported: 42084 spp (vs 42074 spp)
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct taxa: OK (356 spp, 116 gen, 6 tribes, 14 subfam, 3 fam)

Metrics

<img width="1342" height="6022" alt="Image" src="https://github.com/user-attachments/assets/dd5fc3fa-908b-468d-a4f8-b9d3314a7b77" />

TASKS

<img width="1479" height="873" alt="Image" src="https://github.com/user-attachments/assets/b500077b-0ae5-4cfa-91d0-dc888bd84ef3" />

- Broken decisions, 4 = deleted

Resolved 2025-12-01:

<img width="1479" height="860" alt="Image" src="https://github.com/user-attachments/assets/9eed76cf-de8b-4ea6-bbfc-e4ae76493b2d" />

**Synced 2025-12-01**
